server:
  http_listen_port: 3200

distributor:
  # データ受信設定
  receivers:
    otlp:
      protocols:
        http:
          endpoint: "0.0.0.0:4318"
        grpc:
          endpoint: "0.0.0.0:4317"

compactor:
  compaction:
    block_retention: 24h

storage:
  trace:
    # ローカルファイルシステムを利用
    backend: local 
    local:
      # トレースデータの保存先
      path: /var/tempo
