apiVersion: 1

datasources:
  - name: Tempo
    type: Tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      search:
        hide: false
      tracesToLogs:
        datasourceUid: "loki"
        tags: [
          "job",
          "instance",
          "pod",
          "namespace"
        ]
        mapTagNamesEnabled: false
        spanStartTimeShift: "1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanId: false
