apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      search:
        hide: false
      tracesToLogs:
        datasourceUid: "loki"
        tags: [
          "job",
          "instance",
          "pod",
          "namespace",
          "container",
          "compose_service"
        ]
        mappedTags: [
          {key: "service.name", value: "compose_service"}
        ]
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "+1m"
        filterByTraceID: true
        filterBySpanId: false
        lokiSearch: true
